monitor.bluez.properties = {
    # Default: automatically select best codec (usually AAC)
    # bluez5.codecs = [ sbc, sbc_xq, aac, aptx ]

    # Use default latency offset
    # bluez5.a2dp.latency-offset = 200000
}