context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level       = -11
            rt.prio          = 90
            rtkit.enabled    = false
            rtlimits.enabled = true
        }
        flags = [ ifexists nofail ]
    }
]
