TAB script-binding stats/display-stats-toggle #绑定TAB键为显示播放信息，将用于验证补帧是否生效
Ctrl+1 vf toggle vapoursynth="~~/vs/svpflow.vpy" #绑定Ctrl+1用于开关补帧脚本，你可以用它来对比补帧前后的效果
Ctrl+2 vf toggle vapoursynth="~~/vs/svpflow-low.vpy" #绑定Ctrl+1用于开关补帧脚本，你可以用它来对比补帧前后的效果
