hwdec              = auto-safe      # 指定应使用的硬件视频解码API，默认值 no 为软解。值 auto 或 auto-safe（等效值 yes） 即优先尝试原生硬解，但不支持部分设置/滤镜。

fs                     = yes
save-position-on-quit  = yes
auto-hide-delay = 1

interpolation
video-sync=display-resample
tscale=oversample

# vf-append = vapoursynth="~~/vs/svpflow.vpy"
# vf-append = vapoursynth="~~/vs/memc_rife_nv.vpy"
audio-buffer=0.5
video-sync=display-resample
